# docker-compose.yml
services:
  backend:
    build: .
    image: myapp:py
    container_name: myapp-backend
    command: ["uvicorn", "app.server:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build: .
    image: myapp:py
    container_name: myapp-frontend
    command: ["streamlit", "run", "ui/app.py", "--server.port", "8501", "--server.address", "0.0.0.0"]
    ports:
      - "8501:8501"
    depends_on:
      - backend
    restart: unless-stopped
